# web: gunicorn --pythonpath sechand_backend sechand_backend.wsgi
# web: daphne -host 0.0.0.0 -p $PORT sechand_backend.asgi:application
# web: gunicorn sechand_backend.asgi:application -k uvicorn.workers.UvicornWorker
web: daphne your_project.asgi:application --port $PORT --bind 0.0.0.0