# Generated by Django 5.0.1 on 2024-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
