# Generated by Django 5.0.1 on 2024-04-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
