# Generated by Django 5.0.1 on 2024-02-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(default='Elaine', max_length=30),
            preserve_default=False,
        ),
    ]
