# Generated by Django 5.0.1 on 2024-02-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_displayname'),
        ('user', '0004_customuser_is_verified'),
    ]

    operations = [
    ]
