# Generated by Django 5.0.1 on 2024-04-01 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranSaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField()),
                ('seller_id', models.BigIntegerField()),
                ('buyer_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
