# Generated by Django 5.0.1 on 2024-02-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='catagory',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
