# Generated by Django 5.0.1 on 2024-02-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_item_tags_item_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
    ]
