# Generated by Django 5.0.1 on 2024-02-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_catagory_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_id',
            new_name='user',
        ),
    ]
