# Generated by Django 5.0.1 on 2024-04-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='transaction',
            name='review',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
