# Generated by Django 5.0.1 on 2024-02-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_user_id_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='seller',
        ),
    ]
