# Generated by Django 5.0.1 on 2024-03-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_usercollection_userpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
