name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    name: Deploy Vue App to Vercel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        working-directory: ./sechand
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./sechand
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./sechand
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./sechand
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}